from app.models import (
    AnalysisReport,
)


class GitHubMarkdownRenderer:
    """
    Renders an AnalysisReport as GitHub-flavored Markdown.
    """

    REPORT_MARKER = "<!-- TERRAGUARD_REPORT -->"

    def render(
        self,
        report: AnalysisReport,
    ) -> str:

        lines = []

        decision = report.decision.decision.value

        total_resources = len(report.risk_report.resources)

        resources_with_findings = sum(
            resource.has_findings() for resource in report.risk_report.resources
        )

        total_findings = sum(
            resource.total_findings() for resource in report.risk_report.resources
        )

        lines.append("# TerraGuard Analysis")
        lines.append("")

        lines.append("## Deployment Decision")
        lines.append("")
        lines.append(f"**{decision}**")
        lines.append("")

        lines.append("---")
        lines.append("")

        lines.append("## Summary")
        lines.append("")

        lines.append("| Metric | Value |")
        lines.append("|:-------|------:|")
        lines.append(f"| Deployment Decision | {decision} |")
        lines.append(f"| Resources Analyzed | {total_resources} |")
        lines.append(f"| Resources with Findings | {resources_with_findings} |")
        lines.append(f"| Total Security Findings | {total_findings} |")

        lines.append("")
        lines.append("---")
        lines.append("")

        lines.append("## Resource Risk Summary")
        lines.append("")

        lines.append("| Resource | Risk | Findings | Graph Score |")
        lines.append("|:---------|:-----|----------:|------------:|")

        for resource in report.risk_report.resources:

            lines.append(
                f"| "
                f"{resource.criticality.resource} | "
                f"{resource.risk_level()} | "
                f"{resource.total_findings()} | "
                f"{resource.criticality.score} |"
            )

        lines.append("")
        lines.append("---")
        lines.append("")

        lines.append("## Recommendations")
        lines.append("")

        for index, recommendation in enumerate(
            report.decision.recommendations,
            start=1,
        ):

            lines.append(f"{index}. {recommendation}")

        lines.append("")
        lines.append("---")
        lines.append("")

        # Invisible marker used to identify TerraGuard comments.
        lines.append(self.REPORT_MARKER)

        lines.append("")
        lines.append("_Generated by TerraGuard v0.1.0_")

        return "\n".join(lines)
